"""initial schema

Revision ID: 3143b89fa08e
Revises: 
Create Date: 2026-07-09 11:19:12.605279

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3143b89fa08e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('fts', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('product', 'service', 'flow', 'institutional', 'faq')", name='ck_kb_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("kb_entries_fts_gin", "kb_entries", ["fts"], postgresql_using="gin")
    op.create_index("kb_entries_category_ix", "kb_entries", ["category"])
    op.create_index("kb_entries_embedding_null_ix", "kb_entries", ["embedding"], postgresql_where=sa.text("embedding IS NULL"))
    op.execute("CREATE INDEX kb_entries_embedding_hnsw ON kb_entries USING hnsw (embedding vector_cosine_ops)")
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'user')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("threads_user_id_ix", "threads", ["user_id"])

    op.create_table('human_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'contacted', 'closed')", name='ck_human_status'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("open_handoffs_ix", "human_requests", ["created_at"], postgresql_where=sa.text("status = 'open'"))

    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'tool')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("messages_thread_id_ix", "messages", ["thread_id"])
    op.create_index("messages_created_at_ix", "messages", ["created_at"])

    op.create_table('unanswered_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('top_sim', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=32), server_default='no_context', nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('no_context', 'injection')", name='ck_unanswered_reason'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("unresolved_ix", "unanswered_questions", ["created_at"], postgresql_where=sa.text("resolved = false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("unresolved_ix", table_name="unanswered_questions")
    op.drop_index("messages_created_at_ix", table_name="messages")
    op.drop_index("messages_thread_id_ix", table_name="messages")
    op.drop_index("open_handoffs_ix", table_name="human_requests")
    op.drop_index("threads_user_id_ix", table_name="threads")
    op.drop_index("kb_entries_embedding_null_ix", table_name="kb_entries")
    op.drop_index("kb_entries_category_ix", table_name="kb_entries")
    op.drop_index("kb_entries_fts_gin", table_name="kb_entries")
    op.execute("DROP INDEX IF EXISTS kb_entries_embedding_hnsw")
    op.drop_table('unanswered_questions')
    op.drop_table('messages')
    op.drop_table('human_requests')
    op.drop_table('threads')
    op.drop_table('users')
    op.drop_table('kb_entries')
